name: Run Tests

on: [push]

jobs:
  tests-on-chrome-ubuntu-20:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v3

      # https://github.com/cypress-io/github-action
      - name: Cypress run 🚀
        uses: cypress-io/github-action@v4

      # you can use Cypress Dashboard to store the screenshots
      # or store them on GitHub and download the zip file
      # https://github.com/actions/upload-artifact
      - name: Save screenshots 🖼
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress-screenshots
          path: cypress/screenshots

  tests-on-ff-ubuntu-20:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout 🛎
        uses: actions/checkout@v3

      # https://github.com/cypress-io/github-action
      - name: Cypress run 🚀
        uses: cypress-io/github-action@v4

      # you can use Cypress Dashboard to store the screenshots
      # or store them on GitHub and download the zip file
      # https://github.com/actions/upload-artifact
      - name: Save screenshots 🖼
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
          browser: firefox
